### PR TITLE
fix: icons alignment 

### LINKED ISSUE #147: [BUG] Speaker social media icons alignment
**Describe the bug**
In event page, the speakers social media icon are not aligned correctly

**To Reproduce**
1. Go to an event page
2. Scroll down to speaker card

**Expected behavior**
the social media icons should be side by side on the same line

**Screenshots**

Capture d’écran, le 2020-04-14 à 20 52 19

### PR DESCRIPTION
**Pull request by aurelienroux**
### PR check list

- [x] The title of the PR is formatted following [conventional commits](https://www.conventionalcommits.org/) format 
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Functionality has been verified and is ready to be code reviewed

### Relevant issues
resolves #147 

## What is the current behavior?
in speaker cards, social media icons are not aligned 

## What is the new behavior?
- display speaker social icons on a line
- if no speaker slides, hide the slides link
- if no sponsors, hide sponsors display

## Other information
- reorganize components folders 

**Does this PR introduce a breaking change?** 

No

### CODE REVIEW

File: components/event/eventSkeleton.vue [hunk 1]
```diff
@@ -0,0 +1,54 @@
+<template>
+  <article>
```
Comment (tlebel) [inline components/event/eventSkeleton.vue:2]: Philosophical question but... do we really need skeleton with a `nuxt generate` site? 
Are we sure the skeleton code is not imported in the final generated file? 
CC @f3ltron

File: components/event/speakerCard.vue [hunk 2]
```diff
@@ -0,0 +1,99 @@
...
+
+    <div v-if="speaker.slides.url" class="mt-8">
+      <span class="text-mtl-infos"> Slides: </span>
+      <a
+        :href="speaker.slides.url"
+        target="_blank"
+        class="font-bold underline text-mtl-primary "
+        >{{ $t('click_here') }}</a
+      >
+    </div>
```
Comment (tlebel) [inline components/event/speakerCard.vue:65]: I know this is a bit out of scope, but let's use this refactor to improve this. We should [avoid "Click here" as much as possible](https://www.smashingmagazine.com/2012/06/links-should-never-say-click-here/) since it's not a good practice. 

Can you put instead a simple link that reads:  
EN: `View slides`
FR: `Voir les diapositives` 

If I understand well you'll have to add the translation here: 

https://github.com/vuemontreal/vuemontreal/blob/928991b80e8cdce6bd76cba9e95f2ec6936a158b/configs/i18n.js#L11-L26

Please also remove / clean up the `click_here` as it's not used anywhere else.


```suggestion
    <div v-if="speaker.slides.url" class="mt-8">
      <a
        :href="speaker.slides.url"
        target="_blank"
        class="font-bold underline text-mtl-primary "
        >{{ $t('view_slides') }}</a
      >
    </div>
```

File: components/event/eventSkeleton.vue (hunk 1 above)
Comment (tlebel) [reply components/event/eventSkeleton.vue:2]: And if it's not needed, I'd simply remove the code. Less code to manage and think about is always better.

Comment (f3ltron) [reply components/event/eventSkeleton.vue:2]: it give use a nice lazy load datas for each successive routes

Comment (tlebel) [reply components/event/eventSkeleton.vue:2]: Ahh ok cool! Yeah I see it now if I put 3G slow!  Great, good thing to have those then!

File: components/event/eventSkeleton.vue [hunk 3]
```diff
@@ -0,0 +1,54 @@
+<template>
```
[the remark this answers is not in the document]
Comment (aurelienroux) [reply components/event/eventSkeleton.vue]: addressed in 92b4d23

File: components/event/speakerCard.vue (hunk 2 above)
Comment (aurelienroux) [reply components/event/speakerCard.vue]: good point! addressed in 38a07d6

File: configs/i18n.js [hunk 4]
```diff
@@ -1,50 +1,50 @@
...
-  vuex: {
-    // Module namespace
-    moduleName: 'i18n',
-    // If enabled, current app's locale is synced with nuxt-i18n store module
-    syncLocale: true,
-    // Mutation to commit to set route parameters translations
-    syncRouteParams: true
-  }
-}
+/* eslint-disable */
```
Comment (tlebel) [inline configs/i18n.js:1]: Please not I've just fixed the CRLF/LF issue we had with a bunch of files. 
Your IDE being properly fixed it automatically in this file - this is why you have a 100% line change here. It should be back to normal after you rebase / merge your branch.

File: components/event/sponsors.vue [hunk 5]
```diff
@@ -0,0 +1,21 @@
...
+    </ul>
+  </div>
+</template>
+
+<script>
+export default {
+  props: {
+    /* eslint-disable vue/require-default-prop */
+    sponsors: Array
+  }
```
Comment (tlebel) [inline components/event/sponsors.vue:19]: I just realised there is a bunch of `/* eslint-...` disabling in this project :\   We should really strive to avoid that as much as possible as they are simply best practices we ignore without any apparent good reason. 

I'll address the others in another ticket, but while we are here, let's fix this one. 
You can try this is should do the trick: 

```suggestion
  props: {
    sponsors: {
      type: Array,
      required: true
    }
  }
```

File: components/event/speakerCard.vue (hunk 2 above)
Comment (tlebel) [reply components/event/speakerCard.vue]: Perfect! 💯

File: components/event/eventSkeleton.vue (hunk 3 above)
[the remark this answers is not in the document]
Comment (tlebel) [reply components/event/eventSkeleton.vue]: Awesome! 🙌

File: components/event/sponsors.vue (hunk 5 above)
Comment (aurelienroux) [reply components/event/sponsors.vue]: 100% agree! and thank you for this one, I could not see where was the error. FYI, there are still some eslint disable rules (every config files has one) but my knowledge of Nuxt is not strong enough to be sure I can remove them without breaking everything 😛 

addressed in 601a0a2

File: configs/i18n.js (hunk 4 above)
Comment (aurelienroux) [reply configs/i18n.js:1]: 👍

File: components/event/sponsors.vue (hunk 5 above)
Comment (tlebel) [reply components/event/sponsors.vue]: Awesome! And yes for the others I've started a branch here https://github.com/vuemontreal/vuemontreal/pull/150 already :)
