### PR TITLE
fix: add back mobile nav left white background

### LINKED ISSUE #185: [BUG] Mobile menu lost its white background
**Describe the bug**

**To Reproduce**
1. Go on the mobile version
2. Open the menu

**Expected behavior**
The menu background should be white not transparent

### PR DESCRIPTION
**Pull request by f3ltron**
### PR check list
- [x] The title of the PR is formatted following [conventional commits](https://www.conventionalcommits.org/) format 
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Functionality has been verified and is ready to be code reviewed

### Relevant issues
Closes #185 

## What is the current behavior?

no background mobile nav-left

## What is the new behavior?

adding the background on nav-left white

**Does this PR introduce a breaking change?** 

no

### CODE REVIEW

File: layouts/default.vue [hunk 1]
```diff
@@ -75,6 +75,7 @@ html {
   display: inherit;
   left: 0;
   transition: 0.3s ease-out;
+  @apply left-0 bg-mtl-white;
```
Comment (fuentesloic) [inline layouts/default.vue:78]: @f3ltron I think we need to add an empty line above like you did in `.card-block`

```JS
.card-block {
  box-shadow: 0 8px 42px rgba(0, 0, 0, 0.08);

  @apply px-4 pb-2 border border-mtl-black-200 rounded-lg relative;
}
```

Comment (fuentesloic) [reply layouts/default.vue:78]: if not just resolve and merge 👍

Comment (f3ltron) [reply layouts/default.vue:78]: we dont have the css lint on master yet. We will follow it after
